### PR TITLE
Add Microsoft.ML.TestModels package.

### PR DESCRIPTION
**Pull request by eerhardt**
This new package can contain ML.NET model .zip files that we can use in our tests.

Initially, I'm adding an older version of a binary loader model to test a bug I introduced.

### CODE REVIEW

**Review by abgoswam — APPROVED** [review]
:shipit:

**Comment by ericstj** [comment]
Any license info needed?

**Comment by ericstj** [comment]
nevermind, I see the size of that zip.

**Review by ericstj — APPROVED** [review]

**Comment by ericstj** [comment]
Package has been built and pushed.  Should be available shortly on dotnet-core feed.

**Comment by eerhardt** [comment]
> Any license info needed?

No, there shouldn't be. It is simply an ML.NET model that has the schema for a binary loader that has 2 string columns: "Image" and "Class". The valuable test-ness of it is that it is in the older version format, and I broke it when I did some model format changes.

> Package has been built and pushed. Should be available shortly on dotnet-core feed.

Awesome! Thanks for the help.

**Pull request merged**
